# Generated by Django 5.2.10 on 2026-01-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Користувач')),
                ('about', models.CharField(max_length=100, verbose_name='Опис')),
                ('full_text', models.TextField(verbose_name='Повна інформація')),
                ('data', models.DateTimeField(verbose_name='Дата публікації')),
            ],
        ),
    ]
